disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - function_body_length
  - opening_brace
  - optional_data_string_conversion
  - trailing_comma

excluded:
  - Carthage
  - Pods
  - fastlane
  - .build
  - ./QRCode


identifier_name:
  excluded:
    - i
    - id

force_cast: warning
