disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - identifier_name
  - cyclomatic_complexity

excluded:
  - Carthage
  - Pods
  - fastlane
  - .build
  - ./QRCode


force_cast: warning
