//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 2 files.
  struct file {
    /// Resource file `mozilla_ev.json`.
    static let mozilla_evJson = Rswift.FileResource(bundle: R.hostingBundle, name: "mozilla_ev", pathExtension: "json")
    /// Resource file `mozilla_trust.json`.
    static let mozilla_trustJson = Rswift.FileResource(bundle: R.hostingBundle, name: "mozilla_trust", pathExtension: "json")
    
    /// `bundle.url(forResource: "mozilla_ev", withExtension: "json")`
    static func mozilla_evJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.mozilla_evJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    /// `bundle.url(forResource: "mozilla_trust", withExtension: "json")`
    static func mozilla_trustJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.mozilla_trustJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 27 images.
  struct image {
    /// Image `CertLargePersonal`.
    static let certLargePersonal = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertLargePersonal")
    /// Image `CertLargeRoot`.
    static let certLargeRoot = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertLargeRoot")
    /// Image `CertLargeStd`.
    static let certLargeStd = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertLargeStd")
    /// Image `CertSmallPersonal_Invalid`.
    static let certSmallPersonal_Invalid = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertSmallPersonal_Invalid")
    /// Image `CertSmallPersonal_UserTrust`.
    static let certSmallPersonal_UserTrust = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertSmallPersonal_UserTrust")
    /// Image `CertSmallPersonal`.
    static let certSmallPersonal = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertSmallPersonal")
    /// Image `CertSmallRoot_Invalid`.
    static let certSmallRoot_Invalid = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertSmallRoot_Invalid")
    /// Image `CertSmallRoot_UserTrust`.
    static let certSmallRoot_UserTrust = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertSmallRoot_UserTrust")
    /// Image `CertSmallRoot`.
    static let certSmallRoot = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertSmallRoot")
    /// Image `CertSmallStd_Invalid`.
    static let certSmallStd_Invalid = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertSmallStd_Invalid")
    /// Image `CertSmallStd_UserTrust`.
    static let certSmallStd_UserTrust = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertSmallStd_UserTrust")
    /// Image `CertSmallStd`.
    static let certSmallStd = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertSmallStd")
    /// Image `CertStackLarge`.
    static let certStackLarge = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertStackLarge")
    /// Image `CertStackSmall`.
    static let certStackSmall = Rswift.ImageResource(bundle: R.hostingBundle, name: "CertStackSmall")
    /// Image `IndicatorH2`.
    static let indicatorH2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "IndicatorH2")
    /// Image `IndicatorNone`.
    static let indicatorNone = Rswift.ImageResource(bundle: R.hostingBundle, name: "IndicatorNone")
    /// Image `WOTExcellent`.
    static let wOTExcellent = Rswift.ImageResource(bundle: R.hostingBundle, name: "WOTExcellent")
    /// Image `WOTGood`.
    static let wOTGood = Rswift.ImageResource(bundle: R.hostingBundle, name: "WOTGood")
    /// Image `WOTPoor`.
    static let wOTPoor = Rswift.ImageResource(bundle: R.hostingBundle, name: "WOTPoor")
    /// Image `WOTUnsatisfactory`.
    static let wOTUnsatisfactory = Rswift.ImageResource(bundle: R.hostingBundle, name: "WOTUnsatisfactory")
    /// Image `WOTVeryPoor`.
    static let wOTVeryPoor = Rswift.ImageResource(bundle: R.hostingBundle, name: "WOTVeryPoor")
    /// Image `step1`.
    static let step1 = Rswift.ImageResource(bundle: R.hostingBundle, name: "step1")
    /// Image `step2`.
    static let step2 = Rswift.ImageResource(bundle: R.hostingBundle, name: "step2")
    /// Image `step3`.
    static let step3 = Rswift.ImageResource(bundle: R.hostingBundle, name: "step3")
    /// Image `step4`.
    static let step4 = Rswift.ImageResource(bundle: R.hostingBundle, name: "step4")
    /// Image `step5`.
    static let step5 = Rswift.ImageResource(bundle: R.hostingBundle, name: "step5")
    /// Image `step6`.
    static let step6 = Rswift.ImageResource(bundle: R.hostingBundle, name: "step6")
    
    /// `UIImage(named: "CertLargePersonal", bundle: ..., traitCollection: ...)`
    static func certLargePersonal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certLargePersonal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertLargeRoot", bundle: ..., traitCollection: ...)`
    static func certLargeRoot(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certLargeRoot, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertLargeStd", bundle: ..., traitCollection: ...)`
    static func certLargeStd(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certLargeStd, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertSmallPersonal", bundle: ..., traitCollection: ...)`
    static func certSmallPersonal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certSmallPersonal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertSmallPersonal_Invalid", bundle: ..., traitCollection: ...)`
    static func certSmallPersonal_Invalid(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certSmallPersonal_Invalid, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertSmallPersonal_UserTrust", bundle: ..., traitCollection: ...)`
    static func certSmallPersonal_UserTrust(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certSmallPersonal_UserTrust, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertSmallRoot", bundle: ..., traitCollection: ...)`
    static func certSmallRoot(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certSmallRoot, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertSmallRoot_Invalid", bundle: ..., traitCollection: ...)`
    static func certSmallRoot_Invalid(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certSmallRoot_Invalid, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertSmallRoot_UserTrust", bundle: ..., traitCollection: ...)`
    static func certSmallRoot_UserTrust(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certSmallRoot_UserTrust, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertSmallStd", bundle: ..., traitCollection: ...)`
    static func certSmallStd(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certSmallStd, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertSmallStd_Invalid", bundle: ..., traitCollection: ...)`
    static func certSmallStd_Invalid(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certSmallStd_Invalid, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertSmallStd_UserTrust", bundle: ..., traitCollection: ...)`
    static func certSmallStd_UserTrust(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certSmallStd_UserTrust, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertStackLarge", bundle: ..., traitCollection: ...)`
    static func certStackLarge(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certStackLarge, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "CertStackSmall", bundle: ..., traitCollection: ...)`
    static func certStackSmall(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.certStackSmall, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "IndicatorH2", bundle: ..., traitCollection: ...)`
    static func indicatorH2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.indicatorH2, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "IndicatorNone", bundle: ..., traitCollection: ...)`
    static func indicatorNone(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.indicatorNone, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "WOTExcellent", bundle: ..., traitCollection: ...)`
    static func wOTExcellent(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.wOTExcellent, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "WOTGood", bundle: ..., traitCollection: ...)`
    static func wOTGood(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.wOTGood, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "WOTPoor", bundle: ..., traitCollection: ...)`
    static func wOTPoor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.wOTPoor, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "WOTUnsatisfactory", bundle: ..., traitCollection: ...)`
    static func wOTUnsatisfactory(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.wOTUnsatisfactory, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "WOTVeryPoor", bundle: ..., traitCollection: ...)`
    static func wOTVeryPoor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.wOTVeryPoor, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "step1", bundle: ..., traitCollection: ...)`
    static func step1(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.step1, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "step2", bundle: ..., traitCollection: ...)`
    static func step2(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.step2, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "step3", bundle: ..., traitCollection: ...)`
    static func step3(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.step3, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "step4", bundle: ..., traitCollection: ...)`
    static func step4(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.step4, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "step5", bundle: ..., traitCollection: ...)`
    static func step5(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.step5, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "step6", bundle: ..., traitCollection: ...)`
    static func step6(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.step6, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `kCertificateStackCell`.
    static let kCertificateStackCell: Rswift.ReuseIdentifier<CertificateStackCell> = Rswift.ReuseIdentifier(identifier: "kCertificateStackCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `MainInterface`.
    static let mainInterface = _R.storyboard.mainInterface()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "MainInterface", bundle: ...)`
    static func mainInterface(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.mainInterface)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try mainInterface.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct mainInterface: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = ActionViewController
      
      let actionViewController = StoryboardViewControllerResource<ActionViewController>(identifier: "ActionViewController")
      let bundle = R.hostingBundle
      let name = "MainInterface"
      
      func actionViewController(_: Void = ()) -> ActionViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: actionViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "CertLargeRoot") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'CertLargeRoot' is used in storyboard 'MainInterface', but couldn't be loaded.") }
        if _R.storyboard.mainInterface().actionViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'actionViewController' could not be loaded from storyboard 'MainInterface' as 'ActionViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}