#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
SOURCE="$ROOT_DIR/Packages/InspectCore/Sources/Core/InspectScheme.swift"
OUTPUT="$ROOT_DIR/Extensions/SafariWeb/Resources/generated/inspect-config.js"

scheme=""
certificate_detail_host=""
token_query_item_name=""

while IFS= read -r line; do
  case "$line" in
    *'public static let scheme = "'*)
      value=${line#*public static let scheme = \"}
      scheme=${value%%\"*}
      ;;
    *'public static let certificateDetailHost = "'*)
      value=${line#*public static let certificateDetailHost = \"}
      certificate_detail_host=${value%%\"*}
      ;;
    *'public static let tokenQueryItemName = "'*)
      value=${line#*public static let tokenQueryItemName = \"}
      token_query_item_name=${value%%\"*}
      ;;
  esac
done < "$SOURCE"

mkdir -p "$(dirname "$OUTPUT")"
cat > "$OUTPUT" <<EOF
// Generated by scripts/generate_safari_web_config.sh
globalThis.inspectConfig = {
  deepLink: {
    scheme: "$scheme",
    certificateDetailHost: "$certificate_detail_host",
    tokenQueryItemName: "$token_query_item_name"
  }
};
EOF
