#!/usr/bin/env python3
"""Fetch the CT log list and regenerate KnownCTLogs.swift."""

import base64
import json
import urllib.request
from datetime import date
from pathlib import Path

LOG_LIST_URL = "https://www.gstatic.com/ct/log_list/v3/log_list.json"
OUTPUT = Path(__file__).resolve().parent.parent / "Packages/InspectCore/Sources/Core/KnownCTLogs.swift"

USABLE_STATES = {"usable", "qualified", "pending"}


def fetch_log_list():
    with urllib.request.urlopen(LOG_LIST_URL) as resp:
        return json.loads(resp.read())


def build_entries(data):
    entries = []
    for op in data.get("operators", []):
        op_name = op["name"]
        all_logs = op.get("logs", []) + op.get("tiled_logs", [])
        for log in all_logs:
            state = log.get("state", {})
            if state and not (set(state.keys()) & USABLE_STATES):
                continue

            log_id_bytes = base64.b64decode(log["log_id"])
            description = log.get("description", "")

            display = description.removesuffix(" log").strip()
            if not display:
                display = f"{op_name} (unknown)"

            entries.append((op_name, log_id_bytes, display))

    return entries


def format_byte_literal(raw_bytes):
    return ", ".join(f"0x{b:02X}" for b in raw_bytes)


def render_swift(entries, today):
    lines = [
        "// This file is auto-generated by scripts/update_ct_logs.py",
        f"// Source: {LOG_LIST_URL}",
        "// Do not edit manually.",
        "",
        "import Foundation",
        "",
        "enum KnownCTLogs {",
        "    static func name(forLogID logID: [UInt8]) -> String {",
        "        if let name = knownLogs[Data(logID)] {",
        "            return name",
        "        }",
        "        let truncated = Array(logID.prefix(8)).inspectHexString(grouped: true)",
        '        return "Unknown (\\(truncated)…)"',
        "    }",
        "",
        "    // Log ID (SHA-256 of log's public key) → human-readable name",
        f"    // Last updated: {today}",
        "    private static let knownLogs: [Data: String] = [",
    ]

    current_op = None
    for op_name, log_id_bytes, display in entries:
        if op_name != current_op:
            if current_op is not None:
                lines.append("")
            lines.append(f"        // {op_name}")
            current_op = op_name
        hex_id = log_id_bytes.hex().upper()
        byte_lit = format_byte_literal(log_id_bytes)
        lines.append(f"        // {hex_id}")
        lines.append(f'        Data([{byte_lit}]): "{display}",')

    lines.append("    ]")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    data = fetch_log_list()
    entries = build_entries(data)
    today = date.today().isoformat()
    swift = render_swift(entries, today)

    OUTPUT.write_text(swift)
    print(f"Wrote {len(entries)} CT log entries to {OUTPUT}")


if __name__ == "__main__":
    main()
