#!/usr/bin/env python3
"""Fetch the CT log list and regenerate KnownCTLogs.swift."""

import base64
import json
import urllib.request
from datetime import date
from pathlib import Path

LOG_LIST_URL = "https://www.gstatic.com/ct/log_list/v3/log_list.json"
OUTPUT = Path(__file__).resolve().parent.parent / "Packages/InspectCore/Sources/Core/KnownCTLogs.swift"


def fetch_log_list():
    with urllib.request.urlopen(LOG_LIST_URL) as resp:
        return json.loads(resp.read())


def build_entries(data):
    entries = []
    for op in data.get("operators", []):
        op_name = op["name"]
        all_logs = op.get("logs", []) + op.get("tiled_logs", [])
        for log in all_logs:
            log_id_b64 = log["log_id"]
            log_id_hex = base64.b64decode(log_id_b64).hex().upper()
            description = log.get("description", "")

            display = description.removesuffix(" log").strip()
            if not display:
                display = f"{op_name} (unknown)"

            entries.append((op_name, log_id_hex, display))

    return entries


def render_swift(entries, today):
    lines = []
    lines.append("// This file is auto-generated by scripts/update_ct_logs.py")
    lines.append(f"// Source: {LOG_LIST_URL}")
    lines.append("// Do not edit manually.")
    lines.append("")
    lines.append("enum KnownCTLogs {")
    lines.append("    static func name(forLogID logID: [UInt8]) -> String {")
    lines.append("        let hex = logID.inspectHexString(grouped: false)")
    lines.append("        if let name = knownLogs[hex] {")
    lines.append("            return name")
    lines.append("        }")
    lines.append("        let truncated = Array(logID.prefix(8)).inspectHexString(grouped: true)")
    lines.append('        return "Unknown (\\(truncated)…)"')
    lines.append("    }")
    lines.append("")
    lines.append("    // Log ID (SHA-256 of log's public key) → human-readable name")
    lines.append(f"    // Last updated: {today}")
    lines.append("    static let knownLogs: [String: String] = [")

    current_op = None
    for op_name, log_id_hex, display in entries:
        if op_name != current_op:
            if current_op is not None:
                lines.append("")
            lines.append(f"        // {op_name}")
            current_op = op_name
        lines.append(f'        "{log_id_hex}": "{display}",')

    lines.append("    ]")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    data = fetch_log_list()
    entries = build_entries(data)
    today = date.today().isoformat()
    swift = render_swift(entries, today)

    OUTPUT.write_text(swift)
    print(f"Wrote {len(entries)} CT log entries to {OUTPUT}")


if __name__ == "__main__":
    main()
